R/eval.r

fix for typo and punctuation in doc of evaluate in ./R/eval.r

typos and punctuation

---

R/eval.r
R/parse.r

this adds an optional `filename` to `parse_all` and `evaluate`.
it defaults to sensible values:
* the previous default `<text>` for parsing of `character` strings
* the description of a `connection` (so the URL for `url`, path for `file`/`gzfile`/..., or command line for `pipe`)
* for `functions`, either the existing `fileref` is used or simply `<function>`.
* for the default method, it uses `<expression>`

add “filename” parameter

---

DESCRIPTION
NEWS
R/eval.r
R/replay.r

It implements my feature request #68 . 
If you have no objections to my implementation, please merge it upstream. That would make my life much easier.

Possibility to include timing information to each evaluated command

---

DESCRIPTION
NEWS
R/parse.r

Alternate solution to: https://github.com/hadley/evaluate/issues/74

Use original source for evaluating call objects

---

DESCRIPTION
NEWS
R/parse.r

Still need to triple check this but I think this should fix #77. It seems easier too.

Use default method for parsing calls: fix #77

---

DESCRIPTION
NEWS
R/eval.r
tests/testthat/test-evaluate.r

(This PR fixes https://github.com/yihui/knitr/issues/1425 partly)
According to `?options`:
1. If warn is negative all warnings are ignored.
1. If warn is zero (the default) warnings are stored until the top–level function returns.
1. If warn is one, warnings are printed as they occur.
1. If warn is two or larger all warnings are turned into errors.
But, since [`withCallingHandlers()` doesn't respect `options(warn)`](https://github.com/yihui/knitr/issues/610#issuecomment-25057284), we need some tweaks to emulate the behavior; The default behavior of `evaluate()` is 3, 1. was fixed by yihui's commit (https://github.com/hadley/evaluate/commit/2caeebde0dd56c3d0bd9bf03ced1c66129d6b6b4) long ago, and 2. and 4. are not addressed so far.
This PR fixes 4. If `option(warn)` is 2 or larger, an error …

Do not handle warnings when option(warn) >= 2

---

R/traceback.r

The warnings no longer occur with this pull request. Do we need a test?
``` r
options(warnPartialMatchDollar = TRUE)
e <- structure(list(message = "oops"), class = c("error", "condition"))
evaluate::try_capture_stack({
stop(e)
})
#> Warning: partial match of 'call' to 'calls'
#> Warning: partial match of 'call' to 'calls'
#> <error in list(): oops>
```
> Created on 2018-02-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Avoid warnings for partial matching for incomplete error objects

---

tests/testthat/test-evaluate.r

As discussed on https://github.com/r-lib/evaluate/pull/81#issuecomment-367685196, testthat 2.0.0 won't let warnings promote as errors, which should occur when `option("warn")` is >=2. So, commenting out the test is reasonable (at least, for now).

Skip a failing test about option(warn) >= 2

---

DESCRIPTION
NEWS.md
R/eval.r
R/output.r
man/new_output_handler.Rd
tests/testthat/test-evaluate.r

Registered in the innermost context so that they are called before capture with `try()`.
This allows registering `rlang::entrace()` to enrich all base errors and enable usage of `last_error()` in Rmd chunk.
Progress towards tidyverse/reprex#230.
cc @hadley @jennybc

Allow user-supplied calling handlers

---

.Rbuildignore
DESCRIPTION
NEWS.md
cran-comments.md

@cderv any concerns about me doing a release early next week? (No real urgency just that I want to make sure it's on CRAN before I need to submit pkgdown)

evaluate 0.24

---

R/eval.R
R/parse.R
man/parse_all.Rd
tests/testthat/test-eval.R
tests/testthat/test-parse.R

Make`parse_all()$expr` a list of expressions, where the length is the number of individual expressions within each top-level expression.

Clarify and simplify expr data type

---

R/evaluate-package.R
R/flush-console.R
R/inject-funs.R
tests/testthat/test-flush-console.R

This is the convention we've adopted in the tidyverse because `the` does a nice job of implying that the object is a singleton.

Rename `.env` to `the`

---

R/eval.R
R/graphics.R

@cderv this is a straightforward refactoring, but it's a good place to ask if you have any questions about this pattern of using `defer()` in a wrapper function.

Pull out plot hook registration into our function

---

R/eval.R
R/watcher.R

I think this slightly simplifies the existing code, and as you'll seen in upcoming PRs, allows us to tease apart concerns to yield code that's a little easier to understand.
---
You might be surprised to see me repeatedly growing a list, but this is quite performant in modern versions of R:
```R
f <- function(n) {
output <- watchout()
for (i in 1:n) output$push(1:10)
output$get()
}
bench::mark(
f(10),
f(100),
f(1000),
f(10000),
check = FALSE
)[1:3]
#> # A tibble: 4 × 3
#> expression      min   median
#> <bch:expr> <bch:tm> <bch:tm>
#> 1 f(10)      286.02µs 368.92µs
#> 2 f(100)     352.27µs 442.66µs
#> 3 f(1000)      1.03ms    1.2ms
#> 4 f(10000)     7.79ms   8.49ms
```
(And for older versions of R, I don't think it would the typical length of output is going to cause a performance …

Collect output in an accumulating stack

---

R/watcher.R
tests/testthat/_snaps/watcher.md
tests/testthat/test-watcher.R

I'm not 100% convinced that silently restoring the sink + connection is the correct approach, but it doesn't happen very often and we aren't going to lose much output if we immediately re-open the sink + connection.
Fixes #104 (at least as much as it can be fixed)
It's also worth noting that we're already in a much better place than the released version because we're opening and closing the sink once per chunk, rather than once per top-level expression. That means that you can now use `sink()` within a chunk, which I've added a test for. This PR only affects the behaviour of unbalanced sinks, either closing a sink you didn't open, or opening a sink that you don't close.

Recover from closed sink/closed connection

---

R/eval.R
R/watcher.R

This is a straightforward refactoring to push more logic into the watcher "class".

Helper method to capture plot & output

---

R/eval.R
man/evaluate.Rd
tests/testthat/_snaps/conditions.md
tests/testthat/_snaps/eval.md
tests/testthat/test-conditions.R
tests/testthat/test-eval.R

Like the similar change for `stop_on_error`, I think this change makes it easier to reason about what's going on.
I think this also better captures my original motivation for adding the `log_warnings` argument; you want some way to say "please capture warnings while continuing to show them in the console.". I'm not sure about the field names here, so please let me know if you have better ideas.

Create clearer data structures for keep_message and keep_warning

---

R/parse.R
R/utils.R
tests/testthat/_snaps/replay.md
tests/testthat/helper.R
tests/testthat/test-conditions.R
tests/testthat/test-eval.R
tests/testthat/test-graphics.R
tests/testthat/test-output-handler.R
tests/testthat/test-parse.R
tests/testthat/test-replay.R
tests/testthat/test-watcher.R

The original intent of this code (as much as I can remember) was to make it easier to generate multiline examples by wrapping them in an anonymous zero-argument function (the simplest structure that preserves srcrefs). But I'm not sure the code ever worked properly so I reimplemented it from first principles a considerably cleaner approach.
This is a robust alternative to the testing helper `evaluate_()`, allowing me to eliminate that helper.

Better function parsing

---

R/parse.R
man/parse_all.Rd
tests/testthat/test-parse.R

This makes the output type simpler and makes testing a little easier.

Strip srcrefs from exprs

---

R/eval.R
R/utils.R

This makes the logic a bit more clear, and simplifies the output of `parse_all()`. 
I haven't changed `parse_all()` since it looks like people are relying on this behaviour elsewhere.

Simplify handling of parse failures

---

NEWS.md
R/evaluate.R
R/output-handler.R
R/parse_all.R
man/evaluate.Rd
man/new_output_handler.Rd
man/parse_all.Rd
tests/testthat/test-conditions.R

Use "complete source" instead of top-level expression

---

DESCRIPTION
NEWS.md
R/evaluate.R
R/output-handler.R
R/output.R
R/replay.R
R/watchout.R
R/zzz.R
man/new_output_handler.Rd
tests/testthat/test-graphics.R
tests/testthat/test-replay.R

Fixes #192
This turned out to be rather straightforward to implement after all the refactoring, and while it's unlikely to affect much user code, I think the changes to the tests demonstrates its utility.

Evaluate print in evaluation environment

---

NEWS.md
R/conditions.R
R/evaluate.R
tests/testthat/_snaps/evaluate.md
tests/testthat/test-conditions.R
tests/testthat/test-evaluate.R

Fixes #201
@cderv this has the potential to affect existing Rmds, but I think it's low risk as currently `on.exit()` runs immediately making it effectively useless, so I can't see why anyone would have called it.

Ensure on.exit() runs at end of chunk

---

NEWS.md

0.24 is on CRAN with R>=4.0 required

nit: associate 4.0 dependency bump with the correct version

---

NEWS.md
R/evaluate.R

Fixes #225
I can't remember exactly why this comes up, but clearly in some circumstances rethrowing the error doesn't trigger immediate termination. This shouldn't have widespread effects.
I can't figure out how to test this, but I confirmed that it fixed the reported bug when rendering a qmd.

Always return a bool from restarts

---

DESCRIPTION
tests/testthat/_snaps/conditions/rmd-abort-error.txt
tests/testthat/_snaps/conditions/rmd-stop-error-auto-entrace.txt
tests/testthat/test-conditions.R

rlang 1.1.5 has been released recently and it impacts snapshot by fixing the traceback. 
This PR add minimum requirement and update the snapshot. 
Related to CI error in #235

add rlang min requirement and update snapshot

---

NEWS.md
R/watchout.R
tests/testthat/test-conditions.R
tests/testthat/test-evaluate.R

Because `par("page")` will open a device if one is not already open. Fixes #234.

Prevent `new_device = FALSE` from accidentally opening a device

---

NEWS.md
R/graphics.R
tests/testthat/test-graphics.R

This PR fixes an error I was seeing when running `rmarkdown::render('README.Rmd')` on [thematic's README.Rmd](https://github.com/rstudio/thematic/blob/main/README.Rmd).
Apologies for not having a more minimal reprex, but the problem boils down to the fact that `is.call(x)` returns `TRUE` for `language` objects, which can have this behavior:
```r
x <- expr(pkg::foo())
is.call(x)
#> [1] TRUE
as.character(x[[1]])
#> [1] "::"  "pkg" "foo"
```
So, this change is just more careful about the fact that `as.character(x[[1]])` can have length greater than 1.
```r
> rmarkdown::render("README.Rmd")
processing file: README.Rmd
|.....................................               |  71% [ggrepel]        
Error in `if (as.character(x[[1]]) != "requireNamespace") ...`:
! the condition has length > 1 …
```

Be more careful when detecting grid graphics from call object
